### ISSUE TITLE
Supported boards

### ISSUE THREAD

**Issue by rampa069** [DerAndere1/Marlin2ForPipetBot#24]
Hi, what boards are supported?  I need it with a 6 axis board (i have some STM32 based boards) and want to port to them.

Thanks in advance.

**Comment by DerAndere1** [comment]
Try it with any of the bords you have that are supported by upstream Marlin, make it work and report back. The newer the hardware, the less likely it will work well out of the box. Just do not buy a new board explicitely to test my code. Personally, I can only verify that options listed in https://github.com/DerAndere1/Marlin/issues/13 work. 
In addition, the 6axis_dev branch compiles with Trinamic TMC drivers but you have to test if it works in practice.

**Comment by Aeronut** [comment]
Hi, I'm looking to use 4 axis with a hot wire cutter, reusing a SKR1.3 (LPC1768). 
Without changing any of your dev14 branch, it won't compile due to the following exceptions, which I thought you may be interested in considering you previous comment. On the initial build, all M569 related errors appear along with [2861, 1]. After rebuilding the Intellisense index and running build again, all errors appear.
Initially I thought I had an issue with Intellisense playing up, wouldn't be the first time, but I took a vanilla Marlin 2.0.6 and that built fine.
I'm using VSCode with PlatformIO Core 4.3.4 Home 3.2.3

**M569 - Marlin\src\gcode\feature\trinamic - Lines 25,47,48,55&56 all unterminated #if**
Configuration_store.cpp - Marlin\src\module;
identifier "DEBUG_ERROR_MSG" is undefined [2500, 5]
identifier "DEBUG_ECHO_START" is undefined [2855, 3]
identifier "DEBUG_ECHOLNPGM" is undefined [2856, 3]
**unterminated #if [2861, 1]**
improperly terminated macro invocation [2987, 5]
expected a ')' [3943, 18]
expected '}' at end of input [3943, 18]

I would be interested in your thoughts on the above.

**Comment by DerAndere1** [comment]
Thanks for reporting. I fixed the bug in Marlin\src\gcode\feature\trinamic\M569.cpp.  I am able to build the latest branch https://github.com/DerAndere1/Marlin/tree/6axis_dev with the example configs that can be found in the subfolder configs/examples/DerAndere/ . For the  config in config/examples/DerAndere/RAMPS_MultiAxis/RAMPS_XYZI you also have to replace src/pins/pins_RAMPS.h with config/examples/DerAndere/RAMPS_MultiAxis/RAMPS_XYZI/pins_RAMPS.h . Once you have working configs for the SKR1.3, please attach them together with your modified pins_YOURMOTHERBOARD.h file as a .zip archive to a comment  here. For your specific foamcutter project, you may want to have a look at the following 4axis CAM software: 

**[unpaid advertisement]**

https://www.jedicut.com/en/

**Comment by Aeronut** [comment]
Thanks for the quick lesson on environment/pins dependency and the Jedicut link!
I was able to achieve the above and compile successfully, but once I changed environments and with the specific amendments to pins_BTT_SKR_V1_3.h, I get the following after setting #define NON_E_AXES 4 in configuration.h; 
types.h - could not convert 'o' from 'XYZval<float>' to 'XYZOnlyval<float>' [1283, 112] [1284, 112]
I've raised this as a separate issue, rightly or wrongly.
Almost there, I will upload my config as requested once successful.

**Comment by DerAndere1** [comment]
@Aeronut : make sure you use the 6axis_PR1 branch as of commit https://github.com/DerAndere1/Marlin/commit/0463f537acd30af9ce9c1c36652cb5632929da17 or later.

**Comment by hobiseven** [comment]
@rampa069  I did made the very first tests on an STM32F103, and the basis was working with the foamcutter. You may have to make minor text editions in the Jedicut generated Gcode, but really small ones in the header file. Syntax is not exactly the one of Marlin for feedrates as far as I remember. 

@DerAndere1 Apparently, there are a massive set of contributions from all over the world and yourself. What is the status / upstream marlin. I received a few notifications from Github, and apparently the redesign of the variable structure is overcomed, right? 

Great work you did anyway.!

**Comment by DerAndere1** [comment]
@hobiseven: Yes, after a long coding-pause I revived the project, made the axis names configurable and opened a pull request https://github.com/MarlinFirmware/Marlin/pull/19112 . That move atracted some other skilled contributors so we could properly fix some bugs. Best regards!
